version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip
  - epub
  - pdf

python:
  install:
    - method: "pip"
      path: "."
    - requirements: "docs/requirements.txt"
