name: Python Build and Test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10-dev"]
        architecture: [x86, x64]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        pip install -r dev-requirements.txt
    - name: Build sdist
      run: |
        python setup.py sdist
    - name: Install package
      run: |
        python setup.py develop
    - name: Run tests
      run: |
        pytest -v
    - name: Run linter
      run: |
        flake8
    - name: Run type checker
      run: |
        mypy
