name: Python Build and Test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13-dev"]
        architecture: [x86, x64]
        exclude:
          - os: ubuntu-latest
            architecture: x86

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        pip install -e .[dev]
    - name: Build sdist and wheel
      run: |
        python -m build -s -w
    - name: Run tests
      run: |
        pytest -v
    - name: Run linter
      run: |
        flake8
    - name: Run type checker
      run: |
        mypy
